export default () => ({
  mappings: [
    { id: 'rstick', description: 'testing rstick with b' },
    {
      id: 'rstickbtn',
      modifiers: ['x', 'a'],
      description: 'testing rstickbtn with x and a',
    },
    { id: 'ltrig', description: 'left', modifiers: ['a'] },
    { id: 'lbtn', description: 'left button', modifiers: ['a'] },
    { id: 'ltrig', description: 'left', modifiers: ['a'] },
    { id: 'rtrig', description: 'right trigger', modifiers: ['a'] },
    { id: 'rbtn', description: 'right button', modifiers: ['a'] },
    { id: 'dpad', description: 'dpad', modifiers: ['a'] },
    { id: 'dpad.left', description: 'left', modifiers: ['a'] },
    { id: 'dpad.right', description: 'right', modifiers: ['a'] },
    { id: 'dpad.up', description: 'up', modifiers: ['a'] },
    { id: 'dpad.down', description: 'down', modifiers: ['a'] },
    { id: 'view', description: 'view', modifiers: ['a'] },
    { id: 'menu', description: 'menu', modifiers: ['a'] },
    { id: 'lstick', description: 'stick', modifiers: ['a'] },
    { id: 'lstickbtn', description: 'stick', modifiers: ['a'] },
    { id: 'a', description: 'a', modifiers: ['a'] },
    { id: 'x', description: 'x', modifiers: ['a'] },
    { id: 'y', description: 'y', modifiers: ['a'] },
    { id: 'y', description: 'y', modifiers: ['a'] },
    { id: 'b', description: 'b', modifiers: ['a'] },
    { id: 'b', description: 'b', modifiers: ['a'] },
  ],
});
